### ISSUE TITLE
TO-DO List

### ISSUE THREAD

**Issue by AvalancheYT** [SprucyFreedomDevs/SprucyFreedomMod#1]
These are the list I will be working hard for the future releases:

- [ ] Admin Related
  - [ ] Verification System
  - [ ] Make changes around with few commands
  - [ ] Re-work with BukkitTelnet (Make it work for our usage)
- [ ] Fun Related
  - [ ] Double Jump
  - [ ] Make a few changes around with Jumppads
  - [ ] Disguise? (Able to disguise as a mob, if disguised, they can't break/place blocks)

@XGreenPlayz12
